# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ammirzae <ammirzae@student.42vienna.c      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2026/04/27 17:33:51 by ammirzae          #+#    #+#              #
#    Updated: 2026/04/27 17:34:47 by ammirzae         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRC = ft_atoi.c ft_isalpha.c ft_memchr.c ft_memset.c\ 
	ft_strjoin.c ft_strncmp.c ft_tolower.c ft_bzero.c\
	ft_isascii.c ft_memcmp.c ft_split.c ft_strlcat.c\
	ft_strnstr.c ft_toupper.c ft_calloc.c ft_isdigit.c\
	ft_memcpy.c ft_strchr.c ft_strlcpy.c ft_strrchr.c\
	ft_isalnum.c ft_isprint.c ft_memmove.c ft_strdup.c\
	ft_strlen.c  ft_substr.c\

