NAME = maker.out

SRC =	ft_lstnew.c/
	ft_lstadd_front.c/
	ft_lstlast.c/
	ft_lstsize.c/
	ft_lstadd_back.c/
	ft_lstdelone.c/
	ft_lstclear.c/
	ft_lstiter.c/

#OBJ = (SRC:.c=.o)

FLAGS = -Wall -Wextra 

all: $(NAME)

$(NAME):
	cc $(FLAGS) $(SRC) -o $(NAME)

